apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: vulnerabilities.kubetrivy.io
spec:
  group: kubetrivy.io
  version: v1
  names:
    kind: Vulnerability
    plural: vulnerabilities
  scope: Namespaced
  additionalPrinterColumns:
  - name: UNKNOWN
    type: integer
    description: The total of vulnerabilities launched by the kubetrivy
    JSONPath: .spec.statistics.UNKNOWN
  - name: LOW
    type: integer
    description: The total of vulnerabilities launched by the kubetrivy
    JSONPath: .spec.statistics.LOW
  - name: MEDIUM
    type: integer
    description: The total of vulnerabilities launched by the kubetrivy
    JSONPath: .spec.statistics.MEDIUM
  - name: HIGH
    type: integer
    description: The total of vulnerabilities launched by the kubetrivy
    JSONPath: .spec.statistics.HIGH
  - name: CRITICAL
    type: integer
    description: The total of vulnerabilities launched by the kubetrivy
    JSONPath: .spec.statistics.CRITICAL
