apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kube-trivy.fullname" . }}
  labels:
{{ include "kube-trivy.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "kube-trivy.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "kube-trivy.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
        - mountPath: "{{ .Values.kubetrivy.configPath }}/cache-dir"
          name: cache-dir
        - mountPath: {{ .Values.kubetrivy.configPath }}
          name: config
      volumes:
      - name: config
        configMap:
          name: {{ template "kube-trivy.fullname" . }}
      - name: cache-dir
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim | default (include "kube-trivy.fullname" .) }}
      {{- else }}
        emptyDir: {}
      {{ end }}
