kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "kube-trivy.fullname" . }}-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: {{ template "kube-trivy.fullname" . }}
  namespace: default
roleRef:
  kind: ClusterRole
  name: {{ template "kube-trivy.fullname" . }}-clusterrole
  apiGroup: rbac.authorization.k8s.io
